### ISSUE TITLE
VUE SSR Issue 

### ISSUE THREAD

**Issue by EranGrin** [tserkov/vue-plugin-load-script#28]
The usage of `export default LoadScript` seem to break vue ssr server entry, I could fix this locally
while changing the export to common js `module.exports = LoadScript;`

**Comment by tserkov** [comment]
Hi EranGrin,

I did some testing with Nuxt and found a solution. Since this plugin is exported as an ES6 module, you'll need to tell Nuxt to transpile the plugin.
```javascript
// nuxt.config.js
export default {
  //...
  build: {
    //...
    transpile: ['vue-plugin-load-script'],
    //...
  },
  //...
}
```
And everything should work perfectly! 😃 

I'll add this to the README.

**Comment by EranGrin** [comment]
Hi Tserkov, 
I also found a simple solution, that seems to work without messing up with the webpack configuration.

https://github.com/EranGrin/vue-plugin-load-script/commit/143c37bc030739745c4942bf05f9dcefc33f0251

**Comment by tserkov** [comment]
Hi Eran, 

My concern with changing `export default` to `module.exports =` is that it would very likely break the major version compatibility promise for consuming code.

So while switching it out does work for the specific scenario of SSR, when expected, `module.exports` is a NodeJS-ism, while `export default` only fails with Nuxt because it doesn't transpile ES6 modules by default, contrary to the normal Vue pipeline that does it by default.
