### ISSUE TITLE
Adding defer and async options

### ISSUE THREAD

**Issue by iplanwebsites** [tserkov/vue-plugin-load-script#29]
It'd be useful to be able to pass a flag to enable these options on the generated script tag.

**Comment by tserkov** [comment]
Hi @iplanwebsites, thanks for the suggestion.

Would you be able to explain why a configuration option would be necessary for those properties? The `async` property [is always added](https://github.com/tserkov/vue-plugin-load-script/blob/master/index.js#L10), and `defer` wouldn't have any effect, since scripts passed to this plugin are loaded well [after `DOMContentLoaded` has fired](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer).

**Comment by wywarren** [comment]
In my example scenario when loading the sign in with google script, their docs do it from `https://accounts.google.com/gsi/client` with `defer`. When using this in mounted, I still get a warning from the script saying you're not allow to render a button before initialize. I don't see this warning when loading it from the sample `script` tag with `defer` attribute.
